// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class VW_tbProductosxServicio_View
    {
        public int spro_Id { get; set; }
        public int? serv_Id { get; set; }
        public string serv_Nombre { get; set; }
        public string serv_Descripcion { get; set; }
        public decimal serv_Precio { get; set; }
        public int? prod_Id { get; set; }
        public string prod_Nombre { get; set; }
        public decimal prod_Precio { get; set; }
        public DateTime spro_FechaCreacion { get; set; }
        public int spro_UsuarioCreacion { get; set; }
        public DateTime? spro_FechaModificacion { get; set; }
        public int? spro_UsuarioModificacion { get; set; }
        public bool spro_Estado { get; set; }
    }
}