// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class VW_tbProductos_View
    {
        public int prod_Id { get; set; }
        public string prod_Nombre { get; set; }
        public decimal prod_Precio { get; set; }
        public int cate_Id { get; set; }
        public string cate_Descripcion { get; set; }
        public int prod_Stock { get; set; }
        public int? prov_id { get; set; }
        public string prov_NombreEmpresa { get; set; }
        public DateTime prod_FechaCreacion { get; set; }
        public int prod_UsuarioCreacion { get; set; }
        public DateTime? prod_FechaModificacion { get; set; }
        public int? prod_UsuarioModificacion { get; set; }
        public bool prod_Estado { get; set; }
    }
}