// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class VW_tbUsuarios_View
    {
        public int usur_Id { get; set; }
        public string usur_Usuario { get; set; }
        public string usur_Contrasenia { get; set; }
        public int empl_Id { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellido { get; set; }
        public int usur_UsuarioCreacion { get; set; }
        public DateTime usur_FechaCreacion { get; set; }
        public int? usur_UsuarioModificacion { get; set; }
        public DateTime? usur_FechaModificacion { get; set; }
        public bool usur_Estado { get; set; }
    }
}