// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class VW_tbFacturas_Listado
    {
        public int fact_Id { get; set; }
        public int clie_Id { get; set; }
        public string clie_Nombre { get; set; }
        public string clie_Apellido { get; set; }
        public string clie_Telefono { get; set; }
        public int empl_Id_Atendido { get; set; }
        public string NombreAtendido { get; set; }
        public string ApellidoAtendido { get; set; }
        public string TelefonoAtendido { get; set; }
        public int empl_Id_Caja { get; set; }
        public string NombreCaja { get; set; }
        public string ApellidoCaja { get; set; }
        public string TelefonoCaja { get; set; }
        public int metp_Id { get; set; }
        public string metp_Descripcion { get; set; }
        public DateTime fact_Fecha { get; set; }
        public DateTime fact_FechaCreacion { get; set; }
        public int fact_UsuarioCreacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public int? fact_UsuarioModificacion { get; set; }
        public bool fact_Estado { get; set; }
    }
}